<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $municipio1 = new Municipio();$municipio1->nombre = 'Abejones';$municipio1-> distrito_id = 12;$municipio1->save();
        $municipio2 = new Municipio();$municipio2->nombre = 'Acatlán de Pérez Figueroa';$municipio2-> distrito_id = 6;$municipio2->save();
        $municipio3 = new Municipio();$municipio3->nombre = 'Asunción Cacalotepec';$municipio3-> distrito_id = 14;$municipio3->save();
        $municipio4 = new Municipio();$municipio4->nombre = 'Asunción Cuyotepeji';$municipio4-> distrito_id = 2;$municipio4->save();
        $municipio5 = new Municipio();$municipio5->nombre = 'Asunción Ixtaltepec';$municipio5-> distrito_id = 29;$municipio5->save();
        $municipio6 = new Municipio();$municipio6->nombre = 'Asunción Nochixtlán';$municipio6-> distrito_id = 10;$municipio6->save();
        $municipio7 = new Municipio();$municipio7->nombre = 'Asunción Ocotlán';$municipio7-> distrito_id = 25;$municipio7->save();
        $municipio8 = new Municipio();$municipio8->nombre = 'Asunción Tlacolulita';$municipio8-> distrito_id = 27;$municipio8->save();
        $municipio9 = new Municipio();$municipio9->nombre = 'Ayotzintepec';$municipio9-> distrito_id = 6;$municipio9->save();
        $municipio10 = new Municipio();$municipio10->nombre = 'El Barrio de la Soledad';$municipio10-> distrito_id = 29;$municipio10->save();
        $municipio11 = new Municipio();$municipio11->nombre = 'Calihualá';$municipio11-> distrito_id = 1;$municipio11->save();
        $municipio12 = new Municipio();$municipio12->nombre = 'Candelaria Loxicha';$municipio12-> distrito_id = 30;$municipio12->save();
        $municipio13 = new Municipio();$municipio13->nombre = 'Ciénega de Zimatlán';$municipio13-> distrito_id = 18;$municipio13->save();
        $municipio14 = new Municipio();$municipio14->nombre = 'Ciudad Ixtepec';$municipio14-> distrito_id = 29;$municipio14->save();
        $municipio15 = new Municipio();$municipio15->nombre = 'Coatecas Altas';$municipio15-> distrito_id = 24;$municipio15->save();
        $municipio16 = new Municipio();$municipio16->nombre = 'Coicoyán de las Flores';$municipio16-> distrito_id = 8;$municipio16->save();
        $municipio17 = new Municipio();$municipio17->nombre = 'La Compañía';$municipio17-> distrito_id = 24;$municipio17->save();
        $municipio18 = new Municipio();$municipio18->nombre = 'Concepción Buenavista';$municipio18-> distrito_id = 3;$municipio18->save();
        $municipio19 = new Municipio();$municipio19->nombre = 'Concepción Pápalo';$municipio19-> distrito_id = 5;$municipio19->save();
        $municipio20 = new Municipio();$municipio20->nombre = 'Constancia del Rosario';$municipio20-> distrito_id = 15;$municipio20->save();
        $municipio21 = new Municipio();$municipio21->nombre = 'Cosolapa';$municipio21-> distrito_id = 6;$municipio21->save();
        $municipio22 = new Municipio();$municipio22->nombre = 'Cosoltepec';$municipio22-> distrito_id = 2;$municipio22->save();
        $municipio23 = new Municipio();$municipio23->nombre = 'Cuilápam de Guerrero';$municipio23-> distrito_id = 19;$municipio23->save();
        $municipio24 = new Municipio();$municipio24->nombre = 'Cuyamecalco Villa de Zaragoza';$municipio24-> distrito_id = 5;$municipio24->save();
        $municipio25 = new Municipio();$municipio25->nombre = 'Chahuites';$municipio25-> distrito_id = 29;$municipio25->save();
        $municipio26 = new Municipio();$municipio26->nombre = 'Chalcatongo de Hidalgo';$municipio26-> distrito_id = 16;$municipio26->save();
        $municipio27 = new Municipio();$municipio27->nombre = 'Chiquihuitlán de Benito Juárez';$municipio27-> distrito_id = 5;$municipio27->save();
        $municipio28 = new Municipio();$municipio28->nombre = 'Heroica Ciudad de Ejutla de Crespo';$municipio28-> distrito_id = 24;$municipio28->save();
        $municipio29 = new Municipio();$municipio29->nombre = 'Eloxochitlán de Flores Magón';$municipio29-> distrito_id = 4;$municipio29->save();
        $municipio30 = new Municipio();$municipio30->nombre = 'El Espinal';$municipio30-> distrito_id = 29;$municipio30->save();
        $municipio31 = new Municipio();$municipio31->nombre = 'Tamazulápam del Espíritu Santo';$municipio31-> distrito_id = 14;$municipio31->save();
        $municipio32 = new Municipio();$municipio32->nombre = 'Fresnillo de Trujano';$municipio32-> distrito_id = 2;$municipio32->save();
        $municipio33 = new Municipio();$municipio33->nombre = 'Guadalupe Etla';$municipio33-> distrito_id = 11;$municipio33->save();
        $municipio34 = new Municipio();$municipio34->nombre = 'Guadalupe de Ramírez';$municipio34-> distrito_id = 1;$municipio34->save();
        $municipio35 = new Municipio();$municipio35->nombre = 'Guelatao de Juárez';$municipio35-> distrito_id = 12;$municipio35->save();
        $municipio36 = new Municipio();$municipio36->nombre = 'Guevea de Humboldt';$municipio36-> distrito_id = 28;$municipio36->save();
        $municipio37 = new Municipio();$municipio37->nombre = 'Mesones Hidalgo';$municipio37-> distrito_id = 15;$municipio37->save();
        $municipio38 = new Municipio();$municipio38->nombre = 'Villa Hidalgo';$municipio38-> distrito_id = 13;$municipio38->save();
        $municipio39 = new Municipio();$municipio39->nombre = 'Heroica Ciudad de Huajuapan de León';$municipio39-> distrito_id = 2;$municipio39->save();
        $municipio40 = new Municipio();$municipio40->nombre = 'Huautepec';$municipio40-> distrito_id = 4;$municipio40->save();
        $municipio41 = new Municipio();$municipio41->nombre = 'Huautla de Jiménez';$municipio41-> distrito_id = 4;$municipio41->save();
        $municipio42 = new Municipio();$municipio42->nombre = 'Ixtlán de Juárez';$municipio42-> distrito_id = 12;$municipio42->save();
        $municipio43 = new Municipio();$municipio43->nombre = 'Heroica Ciudad de Juchitán de Zaragoza';$municipio43-> distrito_id = 29;$municipio43->save();
        $municipio44 = new Municipio();$municipio44->nombre = 'Loma Bonita';$municipio44-> distrito_id = 6;$municipio44->save();
        $municipio45 = new Municipio();$municipio45->nombre = 'Magdalena Apasco';$municipio45-> distrito_id = 11;$municipio45->save();
        $municipio46 = new Municipio();$municipio46->nombre = 'Magdalena Jaltepec';$municipio46-> distrito_id = 10;$municipio46->save();
        $municipio47 = new Municipio();$municipio47->nombre = 'Santa Magdalena Jicotlán';$municipio47-> distrito_id = 3;$municipio47->save();
        $municipio48 = new Municipio();$municipio48->nombre = 'Magdalena Mixtepec';$municipio48-> distrito_id = 18;$municipio48->save();
        $municipio49 = new Municipio();$municipio49->nombre = 'Magdalena Ocotlán';$municipio49-> distrito_id = 25;$municipio49->save();
        $municipio50 = new Municipio();$municipio50->nombre = 'Magdalena Peñasco';$municipio50-> distrito_id = 16;$municipio50->save();
        $municipio51 = new Municipio();$municipio51->nombre = 'Magdalena Teitipac';$municipio51-> distrito_id = 20;$municipio51->save();
        $municipio52 = new Municipio();$municipio52->nombre = 'Magdalena Tequisistlán';$municipio52-> distrito_id = 28;$municipio52->save();
        $municipio53 = new Municipio();$municipio53->nombre = 'Magdalena Tlacotepec';$municipio53-> distrito_id = 28;$municipio53->save();
        $municipio54 = new Municipio();$municipio54->nombre = 'Magdalena Zahuatlán';$municipio54-> distrito_id = 10;$municipio54->save();
        $municipio55 = new Municipio();$municipio55->nombre = 'Mariscala de Juárez';$municipio55-> distrito_id = 2;$municipio55->save();
        $municipio56 = new Municipio();$municipio56->nombre = 'Mártires de Tacubaya';$municipio56-> distrito_id = 21;$municipio56->save();
        $municipio57 = new Municipio();$municipio57->nombre = 'Matías Romero Avendaño';$municipio57-> distrito_id = 29;$municipio57->save();
        $municipio58 = new Municipio();$municipio58->nombre = 'Mazatlán Villa de Flores';$municipio58-> distrito_id = 4;$municipio58->save();
        $municipio59 = new Municipio();$municipio59->nombre = 'Miahuatlán de Porfirio Díaz';$municipio59-> distrito_id = 26;$municipio59->save();
        $municipio60 = new Municipio();$municipio60->nombre = 'Mixistlán de la Reforma';$municipio60-> distrito_id = 14;$municipio60->save();
        $municipio61 = new Municipio();$municipio61->nombre = 'Monjas';$municipio61-> distrito_id = 26;$municipio61->save();
        $municipio62 = new Municipio();$municipio62->nombre = 'Natividad';$municipio62-> distrito_id = 12;$municipio62->save();
        $municipio63 = new Municipio();$municipio63->nombre = 'Nazareno Etla';$municipio63-> distrito_id = 11;$municipio63->save();
        $municipio64 = new Municipio();$municipio64->nombre = 'Nejapa de Madero';$municipio64-> distrito_id = 27;$municipio64->save();
        $municipio65 = new Municipio();$municipio65->nombre = 'Ixpantepec Nieves';$municipio65-> distrito_id = 1;$municipio65->save();
        $municipio66 = new Municipio();$municipio66->nombre = 'Santiago Niltepec';$municipio66-> distrito_id = 29;$municipio66->save();
        $municipio67 = new Municipio();$municipio67->nombre = 'Oaxaca de Juárez';$municipio67-> distrito_id = 19;$municipio67->save();
        $municipio68 = new Municipio();$municipio68->nombre = 'Ocotlán de Morelos';$municipio68-> distrito_id = 25;$municipio68->save();
        $municipio69 = new Municipio();$municipio69->nombre = 'La Pe';$municipio69-> distrito_id = 24;$municipio69->save();
        $municipio70 = new Municipio();$municipio70->nombre = 'Pinotepa de Don Luis';$municipio70-> distrito_id = 21;$municipio70->save();
        $municipio71 = new Municipio();$municipio71->nombre = 'Pluma Hidalgo';$municipio71-> distrito_id = 30;$municipio71->save();
        $municipio72 = new Municipio();$municipio72->nombre = 'San José del Progreso';$municipio72-> distrito_id = 25;$municipio72->save();
        $municipio73 = new Municipio();$municipio73->nombre = 'Putla Villa de Guerrero';$municipio73-> distrito_id = 15;$municipio73->save();
        $municipio74 = new Municipio();$municipio74->nombre = 'Santa Catarina Quioquitani';$municipio74-> distrito_id = 27;$municipio74->save();
        $municipio75 = new Municipio();$municipio75->nombre = 'Reforma de Pineda';$municipio75-> distrito_id = 29;$municipio75->save();
        $municipio76 = new Municipio();$municipio76->nombre = 'La Reforma';$municipio76-> distrito_id = 15;$municipio76->save();
        $municipio77 = new Municipio();$municipio77->nombre = 'Reyes Etla';$municipio77-> distrito_id = 11;$municipio77->save();
        $municipio78 = new Municipio();$municipio78->nombre = 'Rojas de Cuauhtémoc';$municipio78-> distrito_id = 20;$municipio78->save();
        $municipio79 = new Municipio();$municipio79->nombre = 'Salina Cruz';$municipio79-> distrito_id = 28;$municipio79->save();
        $municipio80 = new Municipio();$municipio80->nombre = 'San Agustín Amatengo';$municipio80-> distrito_id = 24;$municipio80->save();
        $municipio81 = new Municipio();$municipio81->nombre = 'San Agustín Atenango';$municipio81-> distrito_id = 1;$municipio81->save();
        $municipio82 = new Municipio();$municipio82->nombre = 'San Agustín Chayuco';$municipio82-> distrito_id = 21;$municipio82->save();
        $municipio83 = new Municipio();$municipio83->nombre = 'San Agustín de las Juntas';$municipio83-> distrito_id = 19;$municipio83->save();
        $municipio84 = new Municipio();$municipio84->nombre = 'San Agustín Etla';$municipio84-> distrito_id = 11;$municipio84->save();
        $municipio85 = new Municipio();$municipio85->nombre = 'San Agustín Loxicha';$municipio85-> distrito_id = 30;$municipio85->save();
        $municipio86 = new Municipio();$municipio86->nombre = 'San Agustín Tlacotepec';$municipio86-> distrito_id = 16;$municipio86->save();
        $municipio87 = new Municipio();$municipio87->nombre = 'San Agustín Yatareni';$municipio87-> distrito_id = 19;$municipio87->save();
        $municipio88 = new Municipio();$municipio88->nombre = 'San Andrés Cabecera Nueva';$municipio88-> distrito_id = 15;$municipio88->save();
        $municipio89 = new Municipio();$municipio89->nombre = 'San Andrés Dinicuiti';$municipio89-> distrito_id = 2;$municipio89->save();
        $municipio90 = new Municipio();$municipio90->nombre = 'San Andrés Huaxpaltepec';$municipio90-> distrito_id = 21;$municipio90->save();
        $municipio91 = new Municipio();$municipio91->nombre = 'San Andrés Huayápam';$municipio91-> distrito_id = 19;$municipio91->save();
        $municipio92 = new Municipio();$municipio92->nombre = 'San Andrés Ixtlahuaca';$municipio92-> distrito_id = 19;$municipio92->save();
        $municipio93 = new Municipio();$municipio93->nombre = 'San Andrés Lagunas';$municipio93-> distrito_id = 9;$municipio93->save();
        $municipio94 = new Municipio();$municipio94->nombre = 'San Andrés Nuxiño';$municipio94-> distrito_id = 10;$municipio94->save();
        $municipio95 = new Municipio();$municipio95->nombre = 'San Andrés Paxtlán';$municipio95-> distrito_id = 26;$municipio95->save();
        $municipio96 = new Municipio();$municipio96->nombre = 'San Andrés Sinaxtla';$municipio96-> distrito_id = 10;$municipio96->save();
        $municipio97 = new Municipio();$municipio97->nombre = 'San Andrés Solaga';$municipio97-> distrito_id = 13;$municipio97->save();
        $municipio98 = new Municipio();$municipio98->nombre = 'San Andrés Teotilálpam';$municipio98-> distrito_id = 5;$municipio98->save();
        $municipio99 = new Municipio();$municipio99->nombre = 'San Andrés Tepetlapa';$municipio99-> distrito_id = 1;$municipio99->save();
        $municipio100 = new Municipio();$municipio100->nombre = 'San Andrés Yaá';$municipio100-> distrito_id = 13;$municipio100->save();
        $municipio101 = new Municipio();$municipio101->nombre = 'San Andrés Zabache';$municipio101-> distrito_id = 24;$municipio101->save();
        $municipio102 = new Municipio();$municipio102->nombre = 'San Andrés Zautla';$municipio102-> distrito_id = 11;$municipio102->save();
        $municipio103 = new Municipio();$municipio103->nombre = 'San Antonino Castillo Velasco';$municipio103-> distrito_id = 25;$municipio103->save();
        $municipio104 = new Municipio();$municipio104->nombre = 'San Antonino el Alto';$municipio104-> distrito_id = 18;$municipio104->save();
        $municipio105 = new Municipio();$municipio105->nombre = 'San Antonino Monte Verde';$municipio105-> distrito_id = 9;$municipio105->save();
        $municipio106 = new Municipio();$municipio106->nombre = 'San Antonio Acutla';$municipio106-> distrito_id = 9;$municipio106->save();
        $municipio107 = new Municipio();$municipio107->nombre = 'San Antonio de la Cal';$municipio107-> distrito_id = 19;$municipio107->save();
        $municipio108 = new Municipio();$municipio108->nombre = 'San Antonio Huitepec';$municipio108-> distrito_id = 17;$municipio108->save();
        $municipio109 = new Municipio();$municipio109->nombre = 'San Antonio Nanahuatípam';$municipio109-> distrito_id = 4;$municipio109->save();
        $municipio110 = new Municipio();$municipio110->nombre = 'San Antonio Sinicahua';$municipio110-> distrito_id = 16;$municipio110->save();
        $municipio111 = new Municipio();$municipio111->nombre = 'San Antonio Tepetlapa';$municipio111-> distrito_id = 21;$municipio111->save();
        $municipio112 = new Municipio();$municipio112->nombre = 'San Baltazar Chichicápam';$municipio112-> distrito_id = 25;$municipio112->save();
        $municipio113 = new Municipio();$municipio113->nombre = 'San Baltazar Loxicha';$municipio113-> distrito_id = 30;$municipio113->save();
        $municipio114 = new Municipio();$municipio114->nombre = 'San Baltazar Yatzachi el Bajo';$municipio114-> distrito_id = 13;$municipio114->save();
        $municipio115 = new Municipio();$municipio115->nombre = 'San Bartolo Coyotepec';$municipio115-> distrito_id = 19;$municipio115->save();
        $municipio116 = new Municipio();$municipio116->nombre = 'San Bartolomé Ayautla';$municipio116-> distrito_id = 4;$municipio116->save();
        $municipio117 = new Municipio();$municipio117->nombre = 'San Bartolomé Loxicha';$municipio117-> distrito_id = 30;$municipio117->save();
        $municipio118 = new Municipio();$municipio118->nombre = 'San Bartolomé Quialana';$municipio118-> distrito_id = 20;$municipio118->save();
        $municipio119 = new Municipio();$municipio119->nombre = 'San Bartolomé Yucuañe';$municipio119-> distrito_id = 16;$municipio119->save();
        $municipio120 = new Municipio();$municipio120->nombre = 'San Bartolomé Zoogocho';$municipio120-> distrito_id = 13;$municipio120->save();
        $municipio121 = new Municipio();$municipio121->nombre = 'San Bartolo Soyaltepec';$municipio121-> distrito_id = 9;$municipio121->save();
        $municipio122 = new Municipio();$municipio122->nombre = 'San Bartolo Yautepec';$municipio122-> distrito_id = 27;$municipio122->save();
        $municipio123 = new Municipio();$municipio123->nombre = 'San Bernardo Mixtepec';$municipio123-> distrito_id = 18;$municipio123->save();
        $municipio124 = new Municipio();$municipio124->nombre = 'San Blas Atempa';$municipio124-> distrito_id = 28;$municipio124->save();
        $municipio125 = new Municipio();$municipio125->nombre = 'San Carlos Yautepec';$municipio125-> distrito_id = 27;$municipio125->save();
        $municipio126 = new Municipio();$municipio126->nombre = 'San Cristóbal Amatlán';$municipio126-> distrito_id = 26;$municipio126->save();
        $municipio127 = new Municipio();$municipio127->nombre = 'San Cristóbal Amoltepec';$municipio127-> distrito_id = 16;$municipio127->save();
        $municipio128 = new Municipio();$municipio128->nombre = 'San Cristóbal Lachirioag';$municipio128-> distrito_id = 13;$municipio128->save();
        $municipio129 = new Municipio();$municipio129->nombre = 'San Cristóbal Suchixtlahuaca';$municipio129-> distrito_id = 3;$municipio129->save();
        $municipio130 = new Municipio();$municipio130->nombre = 'San Dionisio del Mar';$municipio130-> distrito_id = 29;$municipio130->save();
        $municipio131 = new Municipio();$municipio131->nombre = 'San Dionisio Ocotepec';$municipio131-> distrito_id = 20;$municipio131->save();
        $municipio132 = new Municipio();$municipio132->nombre = 'San Dionisio Ocotlán';$municipio132-> distrito_id = 25;$municipio132->save();
        $municipio133 = new Municipio();$municipio133->nombre = 'San Esteban Atatlahuca';$municipio133-> distrito_id = 16;$municipio133->save();
        $municipio134 = new Municipio();$municipio134->nombre = 'San Felipe Jalapa de Díaz';$municipio134-> distrito_id = 6;$municipio134->save();
        $municipio135 = new Municipio();$municipio135->nombre = 'San Felipe Tejalápam';$municipio135-> distrito_id = 11;$municipio135->save();
        $municipio136 = new Municipio();$municipio136->nombre = 'San Felipe Usila';$municipio136-> distrito_id = 6;$municipio136->save();
        $municipio137 = new Municipio();$municipio137->nombre = 'San Francisco Cahuacuá';$municipio137-> distrito_id = 23;$municipio137->save();
        $municipio138 = new Municipio();$municipio138->nombre = 'San Francisco Cajonos';$municipio138-> distrito_id = 13;$municipio138->save();
        $municipio139 = new Municipio();$municipio139->nombre = 'San Francisco Chapulapa';$municipio139-> distrito_id = 5;$municipio139->save();
        $municipio140 = new Municipio();$municipio140->nombre = 'San Francisco Chindúa';$municipio140-> distrito_id = 10;$municipio140->save();
        $municipio141 = new Municipio();$municipio141->nombre = 'San Francisco del Mar';$municipio141-> distrito_id = 29;$municipio141->save();
        $municipio142 = new Municipio();$municipio142->nombre = 'San Francisco Huehuetlán';$municipio142-> distrito_id = 4;$municipio142->save();
        $municipio143 = new Municipio();$municipio143->nombre = 'San Francisco Ixhuatán';$municipio143-> distrito_id = 29;$municipio143->save();
        $municipio144 = new Municipio();$municipio144->nombre = 'San Francisco Jaltepetongo';$municipio144-> distrito_id = 10;$municipio144->save();
        $municipio145 = new Municipio();$municipio145->nombre = 'San Francisco Lachigoló';$municipio145-> distrito_id = 20;$municipio145->save();
        $municipio146 = new Municipio();$municipio146->nombre = 'San Francisco Logueche';$municipio146-> distrito_id = 26;$municipio146->save();
        $municipio147 = new Municipio();$municipio147->nombre = 'San Francisco Nuxaño';$municipio147-> distrito_id = 10;$municipio147->save();
        $municipio148 = new Municipio();$municipio148->nombre = 'San Francisco Ozolotepec';$municipio148-> distrito_id = 26;$municipio148->save();
        $municipio149 = new Municipio();$municipio149->nombre = 'San Francisco Sola';$municipio149-> distrito_id = 23;$municipio149->save();
        $municipio150 = new Municipio();$municipio150->nombre = 'San Francisco Telixtlahuaca';$municipio150-> distrito_id = 11;$municipio150->save();
        $municipio151 = new Municipio();$municipio151->nombre = 'San Francisco Teopan';$municipio151-> distrito_id = 3;$municipio151->save();
        $municipio152 = new Municipio();$municipio152->nombre = 'San Francisco Tlapancingo';$municipio152-> distrito_id = 1;$municipio152->save();
        $municipio153 = new Municipio();$municipio153->nombre = 'San Gabriel Mixtepec';$municipio153-> distrito_id = 22;$municipio153->save();
        $municipio154 = new Municipio();$municipio154->nombre = 'San Ildefonso Amatlán';$municipio154-> distrito_id = 26;$municipio154->save();
        $municipio155 = new Municipio();$municipio155->nombre = 'San Ildefonso Sola';$municipio155-> distrito_id = 23;$municipio155->save();
        $municipio156 = new Municipio();$municipio156->nombre = 'San Ildefonso Villa Alta';$municipio156-> distrito_id = 13;$municipio156->save();
        $municipio157 = new Municipio();$municipio157->nombre = 'San Jacinto Amilpas';$municipio157-> distrito_id = 19;$municipio157->save();
        $municipio158 = new Municipio();$municipio158->nombre = 'San Jacinto Tlacotepec';$municipio158-> distrito_id = 23;$municipio158->save();
        $municipio159 = new Municipio();$municipio159->nombre = 'San Jerónimo Coatlán';$municipio159-> distrito_id = 26;$municipio159->save();
        $municipio160 = new Municipio();$municipio160->nombre = 'San Jerónimo Silacayoapilla';$municipio160-> distrito_id = 2;$municipio160->save();
        $municipio161 = new Municipio();$municipio161->nombre = 'San Jerónimo Sosola';$municipio161-> distrito_id = 11;$municipio161->save();
        $municipio162 = new Municipio();$municipio162->nombre = 'San Jerónimo Taviche';$municipio162-> distrito_id = 25;$municipio162->save();
        $municipio163 = new Municipio();$municipio163->nombre = 'San Jerónimo Tecóatl';$municipio163-> distrito_id = 4;$municipio163->save();
        $municipio164 = new Municipio();$municipio164->nombre = 'San Jorge Nuchita';$municipio164-> distrito_id = 2;$municipio164->save();
        $municipio165 = new Municipio();$municipio165->nombre = 'San José Ayuquila';$municipio165-> distrito_id = 2;$municipio165->save();
        $municipio166 = new Municipio();$municipio166->nombre = 'San José Chiltepec';$municipio166-> distrito_id = 6;$municipio166->save();
        $municipio167 = new Municipio();$municipio167->nombre = 'San José del Peñasco';$municipio167-> distrito_id = 26;$municipio167->save();
        $municipio168 = new Municipio();$municipio168->nombre = 'San José Estancia Grande';$municipio168-> distrito_id = 21;$municipio168->save();
        $municipio169 = new Municipio();$municipio169->nombre = 'San José Independencia';$municipio169-> distrito_id = 6;$municipio169->save();
        $municipio170 = new Municipio();$municipio170->nombre = 'San José Lachiguiri';$municipio170-> distrito_id = 26;$municipio170->save();
        $municipio171 = new Municipio();$municipio171->nombre = 'San José Tenango';$municipio171-> distrito_id = 4;$municipio171->save();
        $municipio172 = new Municipio();$municipio172->nombre = 'San Juan Achiutla';$municipio172-> distrito_id = 16;$municipio172->save();
        $municipio173 = new Municipio();$municipio173->nombre = 'San Juan Atepec';$municipio173-> distrito_id = 12;$municipio173->save();
        $municipio174 = new Municipio();$municipio174->nombre = 'Ánimas Trujano';$municipio174-> distrito_id = 19;$municipio174->save();
        $municipio175 = new Municipio();$municipio175->nombre = 'San Juan Bautista Atatlahuca';$municipio175-> distrito_id = 11;$municipio175->save();
        $municipio176 = new Municipio();$municipio176->nombre = 'San Juan Bautista Coixtlahuaca';$municipio176-> distrito_id = 3;$municipio176->save();
        $municipio177 = new Municipio();$municipio177->nombre = 'San Juan Bautista Cuicatlán';$municipio177-> distrito_id = 5;$municipio177->save();
        $municipio178 = new Municipio();$municipio178->nombre = 'San Juan Bautista Guelache';$municipio178-> distrito_id = 11;$municipio178->save();
        $municipio179 = new Municipio();$municipio179->nombre = 'San Juan Bautista Jayacatlán';$municipio179-> distrito_id = 11;$municipio179->save();
        $municipio180 = new Municipio();$municipio180->nombre = 'San Juan Bautista Lo de Soto';$municipio180-> distrito_id = 21;$municipio180->save();
        $municipio181 = new Municipio();$municipio181->nombre = 'San Juan Bautista Suchitepec';$municipio181-> distrito_id = 2;$municipio181->save();
        $municipio182 = new Municipio();$municipio182->nombre = 'San Juan Bautista Tlacoatzintepec';$municipio182-> distrito_id = 5;$municipio182->save();
        $municipio183 = new Municipio();$municipio183->nombre = 'San Juan Bautista Tlachichilco';$municipio183-> distrito_id = 1;$municipio183->save();
        $municipio184 = new Municipio();$municipio184->nombre = 'San Juan Bautista Tuxtepec';$municipio184-> distrito_id = 6;$municipio184->save();
        $municipio185 = new Municipio();$municipio185->nombre = 'San Juan Cacahuatepec';$municipio185-> distrito_id = 21;$municipio185->save();
        $municipio186 = new Municipio();$municipio186->nombre = 'San Juan Cieneguilla';$municipio186-> distrito_id = 1;$municipio186->save();
        $municipio187 = new Municipio();$municipio187->nombre = 'San Juan Coatzóspam';$municipio187-> distrito_id = 4;$municipio187->save();
        $municipio188 = new Municipio();$municipio188->nombre = 'San Juan Colorado';$municipio188-> distrito_id = 21;$municipio188->save();
        $municipio189 = new Municipio();$municipio189->nombre = 'San Juan Comaltepec';$municipio189-> distrito_id = 7;$municipio189->save();
        $municipio190 = new Municipio();$municipio190->nombre = 'San Juan Cotzocón';$municipio190-> distrito_id = 14;$municipio190->save();
        $municipio191 = new Municipio();$municipio191->nombre = 'San Juan Chicomezúchil';$municipio191-> distrito_id = 12;$municipio191->save();
        $municipio192 = new Municipio();$municipio192->nombre = 'San Juan Chilateca';$municipio192-> distrito_id = 25;$municipio192->save();
        $municipio193 = new Municipio();$municipio193->nombre = 'San Juan del Estado';$municipio193-> distrito_id = 11;$municipio193->save();
        $municipio194 = new Municipio();$municipio194->nombre = 'San Juan del Río';$municipio194-> distrito_id = 20;$municipio194->save();
        $municipio195 = new Municipio();$municipio195->nombre = 'San Juan Diuxi';$municipio195-> distrito_id = 10;$municipio195->save();
        $municipio196 = new Municipio();$municipio196->nombre = 'San Juan Evangelista Analco';$municipio196-> distrito_id = 12;$municipio196->save();
        $municipio197 = new Municipio();$municipio197->nombre = 'San Juan Guelavía';$municipio197-> distrito_id = 20;$municipio197->save();
        $municipio198 = new Municipio();$municipio198->nombre = 'San Juan Guichicovi';$municipio198-> distrito_id = 29;$municipio198->save();
        $municipio199 = new Municipio();$municipio199->nombre = 'San Juan Ihualtepec';$municipio199-> distrito_id = 1;$municipio199->save();
        $municipio200 = new Municipio();$municipio200->nombre = 'San Juan Juquila Mixes';$municipio200-> distrito_id = 27;$municipio200->save();
        $municipio201 = new Municipio();$municipio201->nombre = 'San Juan Juquila Vijanos';$municipio201-> distrito_id = 13;$municipio201->save();
        $municipio202 = new Municipio();$municipio202->nombre = 'San Juan Lachao';$municipio202-> distrito_id = 22;$municipio202->save();
        $municipio203 = new Municipio();$municipio203->nombre = 'San Juan Lachigalla';$municipio203-> distrito_id = 24;$municipio203->save();
        $municipio204 = new Municipio();$municipio204->nombre = 'San Juan Lajarcia';$municipio204-> distrito_id = 27;$municipio204->save();
        $municipio205 = new Municipio();$municipio205->nombre = 'San Juan Lalana';$municipio205-> distrito_id = 7;$municipio205->save();
        $municipio206 = new Municipio();$municipio206->nombre = 'San Juan de los Cués';$municipio206-> distrito_id = 4;$municipio206->save();
        $municipio207 = new Municipio();$municipio207->nombre = 'San Juan Mazatlán';$municipio207-> distrito_id = 14;$municipio207->save();
        $municipio208 = new Municipio();$municipio208->nombre = 'San Juan Mixtepec -Dto. 08 -';$municipio208-> distrito_id = 8;$municipio208->save();
        $municipio209 = new Municipio();$municipio209->nombre = 'San Juan Mixtepec -Dto. 26 -';$municipio209-> distrito_id = 26;$municipio209->save();
        $municipio210 = new Municipio();$municipio210->nombre = 'San Juan Ñumí';$municipio210-> distrito_id = 16;$municipio210->save();
        $municipio211 = new Municipio();$municipio211->nombre = 'San Juan Ozolotepec';$municipio211-> distrito_id = 26;$municipio211->save();
        $municipio212 = new Municipio();$municipio212->nombre = 'San Juan Petlapa';$municipio212-> distrito_id = 7;$municipio212->save();
        $municipio213 = new Municipio();$municipio213->nombre = 'San Juan Quiahije';$municipio213-> distrito_id = 22;$municipio213->save();
        $municipio214 = new Municipio();$municipio214->nombre = 'San Juan Quiotepec';$municipio214-> distrito_id = 12;$municipio214->save();
        $municipio215 = new Municipio();$municipio215->nombre = 'San Juan Sayultepec';$municipio215-> distrito_id = 10;$municipio215->save();
        $municipio216 = new Municipio();$municipio216->nombre = 'San Juan Tabaá';$municipio216-> distrito_id = 13;$municipio216->save();
        $municipio217 = new Municipio();$municipio217->nombre = 'San Juan Tamazola';$municipio217-> distrito_id = 10;$municipio217->save();
        $municipio218 = new Municipio();$municipio218->nombre = 'San Juan Teita';$municipio218-> distrito_id = 16;$municipio218->save();
        $municipio219 = new Municipio();$municipio219->nombre = 'San Juan Teitipac';$municipio219-> distrito_id = 20;$municipio219->save();
        $municipio220 = new Municipio();$municipio220->nombre = 'San Juan Tepeuxila';$municipio220-> distrito_id = 5;$municipio220->save();
        $municipio221 = new Municipio();$municipio221->nombre = 'San Juan Teposcolula';$municipio221-> distrito_id = 9;$municipio221->save();
        $municipio222 = new Municipio();$municipio222->nombre = 'San Juan Yaeé';$municipio222-> distrito_id = 13;$municipio222->save();
        $municipio223 = new Municipio();$municipio223->nombre = 'San Juan Yatzona';$municipio223-> distrito_id = 13;$municipio223->save();
        $municipio224 = new Municipio();$municipio224->nombre = 'San Juan Yucuita';$municipio224-> distrito_id = 10;$municipio224->save();
        $municipio225 = new Municipio();$municipio225->nombre = 'San Lorenzo';$municipio225-> distrito_id = 21;$municipio225->save();
        $municipio226 = new Municipio();$municipio226->nombre = 'San Lorenzo Albarradas';$municipio226-> distrito_id = 20;$municipio226->save();
        $municipio227 = new Municipio();$municipio227->nombre = 'San Lorenzo Cacaotepec';$municipio227-> distrito_id = 11;$municipio227->save();
        $municipio228 = new Municipio();$municipio228->nombre = 'San Lorenzo Cuaunecuiltitla';$municipio228-> distrito_id = 4;$municipio228->save();
        $municipio229 = new Municipio();$municipio229->nombre = 'San Lorenzo Texmelúcan';$municipio229-> distrito_id = 23;$municipio229->save();
        $municipio230 = new Municipio();$municipio230->nombre = 'San Lorenzo Victoria';$municipio230-> distrito_id = 1;$municipio230->save();
        $municipio231 = new Municipio();$municipio231->nombre = 'San Lucas Camotlán';$municipio231-> distrito_id = 14;$municipio231->save();
        $municipio232 = new Municipio();$municipio232->nombre = 'San Lucas Ojitlán';$municipio232-> distrito_id = 6;$municipio232->save();
        $municipio233 = new Municipio();$municipio233->nombre = 'San Lucas Quiaviní';$municipio233-> distrito_id = 20;$municipio233->save();
        $municipio234 = new Municipio();$municipio234->nombre = 'San Lucas Zoquiápam';$municipio234-> distrito_id = 4;$municipio234->save();
        $municipio235 = new Municipio();$municipio235->nombre = 'San Luis Amatlán';$municipio235-> distrito_id = 26;$municipio235->save();
        $municipio236 = new Municipio();$municipio236->nombre = 'San Marcial Ozolotepec';$municipio236-> distrito_id = 26;$municipio236->save();
        $municipio237 = new Municipio();$municipio237->nombre = 'San Marcos Arteaga';$municipio237-> distrito_id = 2;$municipio237->save();
        $municipio238 = new Municipio();$municipio238->nombre = 'San Martín de los Cansecos';$municipio238-> distrito_id = 24;$municipio238->save();
        $municipio239 = new Municipio();$municipio239->nombre = 'San Martín Huamelúlpam';$municipio239-> distrito_id = 16;$municipio239->save();
        $municipio240 = new Municipio();$municipio240->nombre = 'San Martín Itunyoso';$municipio240-> distrito_id = 16;$municipio240->save();
        $municipio241 = new Municipio();$municipio241->nombre = 'San Martín Lachilá';$municipio241-> distrito_id = 24;$municipio241->save();
        $municipio242 = new Municipio();$municipio242->nombre = 'San Martín Peras';$municipio242-> distrito_id = 8;$municipio242->save();
        $municipio243 = new Municipio();$municipio243->nombre = 'San Martín Tilcajete';$municipio243-> distrito_id = 25;$municipio243->save();
        $municipio244 = new Municipio();$municipio244->nombre = 'San Martín Toxpalan';$municipio244-> distrito_id = 4;$municipio244->save();
        $municipio245 = new Municipio();$municipio245->nombre = 'San Martín Zacatepec';$municipio245-> distrito_id = 2;$municipio245->save();
        $municipio246 = new Municipio();$municipio246->nombre = 'San Mateo Cajonos';$municipio246-> distrito_id = 13;$municipio246->save();
        $municipio247 = new Municipio();$municipio247->nombre = 'Capulálpam de Méndez';$municipio247-> distrito_id = 12;$municipio247->save();
        $municipio248 = new Municipio();$municipio248->nombre = 'San Mateo del Mar';$municipio248-> distrito_id = 28;$municipio248->save();
        $municipio249 = new Municipio();$municipio249->nombre = 'San Mateo Yoloxochitlán';$municipio249-> distrito_id = 4;$municipio249->save();
        $municipio250 = new Municipio();$municipio250->nombre = 'San Mateo Etlatongo';$municipio250-> distrito_id = 10;$municipio250->save();
        $municipio251 = new Municipio();$municipio251->nombre = 'San Mateo Nejápam';$municipio251-> distrito_id = 1;$municipio251->save();
        $municipio252 = new Municipio();$municipio252->nombre = 'San Mateo Peñasco';$municipio252-> distrito_id = 16;$municipio252->save();
        $municipio253 = new Municipio();$municipio253->nombre = 'San Mateo Piñas';$municipio253-> distrito_id = 30;$municipio253->save();
        $municipio254 = new Municipio();$municipio254->nombre = 'San Mateo Río Hondo';$municipio254-> distrito_id = 26;$municipio254->save();
        $municipio255 = new Municipio();$municipio255->nombre = 'San Mateo Sindihui';$municipio255-> distrito_id = 10;$municipio255->save();
        $municipio256 = new Municipio();$municipio256->nombre = 'San Mateo Tlapiltepec';$municipio256-> distrito_id = 3;$municipio256->save();
        $municipio257 = new Municipio();$municipio257->nombre = 'San Melchor Betaza';$municipio257-> distrito_id = 13;$municipio257->save();
        $municipio258 = new Municipio();$municipio258->nombre = 'San Miguel Achiutla';$municipio258-> distrito_id = 16;$municipio258->save();
        $municipio259 = new Municipio();$municipio259->nombre = 'San Miguel Ahuehuetitlán';$municipio259-> distrito_id = 1;$municipio259->save();
        $municipio260 = new Municipio();$municipio260->nombre = 'San Miguel Aloápam';$municipio260-> distrito_id = 12;$municipio260->save();
        $municipio261 = new Municipio();$municipio261->nombre = 'San Miguel Amatitlán';$municipio261-> distrito_id = 2;$municipio261->save();
        $municipio262 = new Municipio();$municipio262->nombre = 'San Miguel Amatlán';$municipio262-> distrito_id = 12;$municipio262->save();
        $municipio263 = new Municipio();$municipio263->nombre = 'San Miguel Coatlán';$municipio263-> distrito_id = 26;$municipio263->save();
        $municipio264 = new Municipio();$municipio264->nombre = 'San Miguel Chicahua';$municipio264-> distrito_id = 10;$municipio264->save();
        $municipio265 = new Municipio();$municipio265->nombre = 'San Miguel Chimalapa';$municipio265-> distrito_id = 29;$municipio265->save();
        $municipio266 = new Municipio();$municipio266->nombre = 'San Miguel del Puerto';$municipio266-> distrito_id = 30;$municipio266->save();
        $municipio267 = new Municipio();$municipio267->nombre = 'San Miguel del Río';$municipio267-> distrito_id = 12;$municipio267->save();
        $municipio268 = new Municipio();$municipio268->nombre = 'San Miguel Ejutla';$municipio268-> distrito_id = 24;$municipio268->save();
        $municipio269 = new Municipio();$municipio269->nombre = 'San Miguel el Grande';$municipio269-> distrito_id = 16;$municipio269->save();
        $municipio270 = new Municipio();$municipio270->nombre = 'San Miguel Huautla';$municipio270-> distrito_id = 10;$municipio270->save();
        $municipio271 = new Municipio();$municipio271->nombre = 'San Miguel Mixtepec';$municipio271-> distrito_id = 18;$municipio271->save();
        $municipio272 = new Municipio();$municipio272->nombre = 'San Miguel Panixtlahuaca';$municipio272-> distrito_id = 22;$municipio272->save();
        $municipio273 = new Municipio();$municipio273->nombre = 'San Miguel Peras';$municipio273-> distrito_id = 17;$municipio273->save();
        $municipio274 = new Municipio();$municipio274->nombre = 'San Miguel Piedras';$municipio274-> distrito_id = 10;$municipio274->save();
        $municipio275 = new Municipio();$municipio275->nombre = 'San Miguel Quetzaltepec';$municipio275-> distrito_id = 14;$municipio275->save();
        $municipio276 = new Municipio();$municipio276->nombre = 'San Miguel Santa Flor';$municipio276-> distrito_id = 5;$municipio276->save();
        $municipio277 = new Municipio();$municipio277->nombre = 'Villa Sola de Vega';$municipio277-> distrito_id = 23;$municipio277->save();
        $municipio278 = new Municipio();$municipio278->nombre = 'San Miguel Soyaltepec';$municipio278-> distrito_id = 6;$municipio278->save();
        $municipio279 = new Municipio();$municipio279->nombre = 'San Miguel Suchixtepec';$municipio279-> distrito_id = 26;$municipio279->save();
        $municipio280 = new Municipio();$municipio280->nombre = 'Villa Talea de Castro';$municipio280-> distrito_id = 13;$municipio280->save();
        $municipio281 = new Municipio();$municipio281->nombre = 'San Miguel Tecomatlán';$municipio281-> distrito_id = 10;$municipio281->save();
        $municipio282 = new Municipio();$municipio282->nombre = 'San Miguel Tenango';$municipio282-> distrito_id = 28;$municipio282->save();
        $municipio283 = new Municipio();$municipio283->nombre = 'San Miguel Tequixtepec';$municipio283-> distrito_id = 3;$municipio283->save();
        $municipio284 = new Municipio();$municipio284->nombre = 'San Miguel Tilquiápam';$municipio284-> distrito_id = 25;$municipio284->save();
        $municipio285 = new Municipio();$municipio285->nombre = 'San Miguel Tlacamama';$municipio285-> distrito_id = 21;$municipio285->save();
        $municipio286 = new Municipio();$municipio286->nombre = 'San Miguel Tlacotepec';$municipio286-> distrito_id = 8;$municipio286->save();
        $municipio287 = new Municipio();$municipio287->nombre = 'San Miguel Tulancingo';$municipio287-> distrito_id = 3;$municipio287->save();
        $municipio288 = new Municipio();$municipio288->nombre = 'San Miguel Yotao';$municipio288-> distrito_id = 12;$municipio288->save();
        $municipio289 = new Municipio();$municipio289->nombre = 'San Nicolás';$municipio289-> distrito_id = 26;$municipio289->save();
        $municipio290 = new Municipio();$municipio290->nombre = 'San Nicolás Hidalgo';$municipio290-> distrito_id = 1;$municipio290->save();
        $municipio291 = new Municipio();$municipio291->nombre = 'San Pablo Coatlán';$municipio291-> distrito_id = 26;$municipio291->save();
        $municipio292 = new Municipio();$municipio292->nombre = 'San Pablo Cuatro Venados';$municipio292-> distrito_id = 17;$municipio292->save();
        $municipio293 = new Municipio();$municipio293->nombre = 'San Pablo Etla';$municipio293-> distrito_id = 11;$municipio293->save();
        $municipio294 = new Municipio();$municipio294->nombre = 'San Pablo Huitzo';$municipio294-> distrito_id = 11;$municipio294->save();
        $municipio295 = new Municipio();$municipio295->nombre = 'San Pablo Huixtepec';$municipio295-> distrito_id = 18;$municipio295->save();
        $municipio296 = new Municipio();$municipio296->nombre = 'San Pablo Macuiltianguis';$municipio296-> distrito_id = 12;$municipio296->save();
        $municipio297 = new Municipio();$municipio297->nombre = 'San Pablo Tijaltepec';$municipio297-> distrito_id = 16;$municipio297->save();
        $municipio298 = new Municipio();$municipio298->nombre = 'San Pablo Villa de Mitla';$municipio298-> distrito_id = 20;$municipio298->save();
        $municipio299 = new Municipio();$municipio299->nombre = 'San Pablo Yaganiza';$municipio299-> distrito_id = 13;$municipio299->save();
        $municipio300 = new Municipio();$municipio300->nombre = 'San Pedro Amuzgos';$municipio300-> distrito_id = 15;$municipio300->save();
        $municipio301 = new Municipio();$municipio301->nombre = 'San Pedro Apóstol';$municipio301-> distrito_id = 25;$municipio301->save();
        $municipio302 = new Municipio();$municipio302->nombre = 'San Pedro Atoyac';$municipio302-> distrito_id = 21;$municipio302->save();
        $municipio303 = new Municipio();$municipio303->nombre = 'San Pedro Cajonos';$municipio303-> distrito_id = 13;$municipio303->save();
        $municipio304 = new Municipio();$municipio304->nombre = 'San Pedro Coxcaltepec Cántaros';$municipio304-> distrito_id = 10;$municipio304->save();
        $municipio305 = new Municipio();$municipio305->nombre = 'San Pedro Comitancillo';$municipio305-> distrito_id = 28;$municipio305->save();
        $municipio306 = new Municipio();$municipio306->nombre = 'San Pedro el Alto';$municipio306-> distrito_id = 30;$municipio306->save();
        $municipio307 = new Municipio();$municipio307->nombre = 'San Pedro Huamelula';$municipio307-> distrito_id = 28;$municipio307->save();
        $municipio308 = new Municipio();$municipio308->nombre = 'San Pedro Huilotepec';$municipio308-> distrito_id = 28;$municipio308->save();
        $municipio309 = new Municipio();$municipio309->nombre = 'San Pedro Ixcatlán';$municipio309-> distrito_id = 6;$municipio309->save();
        $municipio310 = new Municipio();$municipio310->nombre = 'San Pedro Ixtlahuaca';$municipio310-> distrito_id = 19;$municipio310->save();
        $municipio311 = new Municipio();$municipio311->nombre = 'San Pedro Jaltepetongo';$municipio311-> distrito_id = 5;$municipio311->save();
        $municipio312 = new Municipio();$municipio312->nombre = 'San Pedro Jicayán';$municipio312-> distrito_id = 21;$municipio312->save();
        $municipio313 = new Municipio();$municipio313->nombre = 'San Pedro Jocotipac';$municipio313-> distrito_id = 5;$municipio313->save();
        $municipio314 = new Municipio();$municipio314->nombre = 'San Pedro Juchatengo';$municipio314-> distrito_id = 22;$municipio314->save();
        $municipio315 = new Municipio();$municipio315->nombre = 'San Pedro Mártir';$municipio315-> distrito_id = 25;$municipio315->save();
        $municipio316 = new Municipio();$municipio316->nombre = 'San Pedro Mártir Quiechapa';$municipio316-> distrito_id = 27;$municipio316->save();
        $municipio317 = new Municipio();$municipio317->nombre = 'San Pedro Mártir Yucuxaco';$municipio317-> distrito_id = 16;$municipio317->save();
        $municipio318 = new Municipio();$municipio318->nombre = 'San Pedro Mixtepec -Dto. 22 -';$municipio318-> distrito_id = 22;$municipio318->save();
        $municipio319 = new Municipio();$municipio319->nombre = 'San Pedro Mixtepec -Dto. 26 -';$municipio319-> distrito_id = 26;$municipio319->save();
        $municipio320 = new Municipio();$municipio320->nombre = 'San Pedro Molinos';$municipio320-> distrito_id = 16;$municipio320->save();
        $municipio321 = new Municipio();$municipio321->nombre = 'San Pedro Nopala';$municipio321-> distrito_id = 9;$municipio321->save();
        $municipio322 = new Municipio();$municipio322->nombre = 'San Pedro Ocopetatillo';$municipio322-> distrito_id = 4;$municipio322->save();
        $municipio323 = new Municipio();$municipio323->nombre = 'San Pedro Ocotepec';$municipio323-> distrito_id = 14;$municipio323->save();
        $municipio324 = new Municipio();$municipio324->nombre = 'San Pedro Pochutla';$municipio324-> distrito_id = 30;$municipio324->save();
        $municipio325 = new Municipio();$municipio325->nombre = 'San Pedro Quiatoni';$municipio325-> distrito_id = 20;$municipio325->save();
        $municipio326 = new Municipio();$municipio326->nombre = 'San Pedro Sochiápam';$municipio326-> distrito_id = 5;$municipio326->save();
        $municipio327 = new Municipio();$municipio327->nombre = 'San Pedro Tapanatepec';$municipio327-> distrito_id = 29;$municipio327->save();
        $municipio328 = new Municipio();$municipio328->nombre = 'San Pedro Taviche';$municipio328-> distrito_id = 25;$municipio328->save();
        $municipio329 = new Municipio();$municipio329->nombre = 'San Pedro Teozacoalco';$municipio329-> distrito_id = 10;$municipio329->save();
        $municipio330 = new Municipio();$municipio330->nombre = 'San Pedro Teutila';$municipio330-> distrito_id = 5;$municipio330->save();
        $municipio331 = new Municipio();$municipio331->nombre = 'San Pedro Tidaá';$municipio331-> distrito_id = 10;$municipio331->save();
        $municipio332 = new Municipio();$municipio332->nombre = 'San Pedro Topiltepec';$municipio332-> distrito_id = 9;$municipio332->save();
        $municipio333 = new Municipio();$municipio333->nombre = 'San Pedro Totolápam';$municipio333-> distrito_id = 20;$municipio333->save();
        $municipio334 = new Municipio();$municipio334->nombre = 'Villa de Tututepec';$municipio334-> distrito_id = 22;$municipio334->save();
        $municipio335 = new Municipio();$municipio335->nombre = 'San Pedro Yaneri';$municipio335-> distrito_id = 12;$municipio335->save();
        $municipio336 = new Municipio();$municipio336->nombre = 'San Pedro Yólox';$municipio336-> distrito_id = 12;$municipio336->save();
        $municipio337 = new Municipio();$municipio337->nombre = 'San Pedro y San Pablo Ayutla';$municipio337-> distrito_id = 14;$municipio337->save();
        $municipio338 = new Municipio();$municipio338->nombre = 'Villa de Etla';$municipio338-> distrito_id = 11;$municipio338->save();
        $municipio339 = new Municipio();$municipio339->nombre = 'San Pedro y San Pablo Teposcolula';$municipio339-> distrito_id = 9;$municipio339->save();
        $municipio340 = new Municipio();$municipio340->nombre = 'San Pedro y San Pablo Tequixtepec';$municipio340-> distrito_id = 2;$municipio340->save();
        $municipio341 = new Municipio();$municipio341->nombre = 'San Pedro Yucunama';$municipio341-> distrito_id = 9;$municipio341->save();
        $municipio342 = new Municipio();$municipio342->nombre = 'San Raymundo Jalpan';$municipio342-> distrito_id = 19;$municipio342->save();
        $municipio343 = new Municipio();$municipio343->nombre = 'San Sebastián Abasolo';$municipio343-> distrito_id = 20;$municipio343->save();
        $municipio344 = new Municipio();$municipio344->nombre = 'San Sebastián Coatlán';$municipio344-> distrito_id = 26;$municipio344->save();
        $municipio345 = new Municipio();$municipio345->nombre = 'San Sebastián Ixcapa';$municipio345-> distrito_id = 21;$municipio345->save();
        $municipio346 = new Municipio();$municipio346->nombre = 'San Sebastián Nicananduta';$municipio346-> distrito_id = 9;$municipio346->save();
        $municipio347 = new Municipio();$municipio347->nombre = 'San Sebastián Río Hondo';$municipio347-> distrito_id = 26;$municipio347->save();
        $municipio348 = new Municipio();$municipio348->nombre = 'San Sebastián Tecomaxtlahuaca';$municipio348-> distrito_id = 8;$municipio348->save();
        $municipio349 = new Municipio();$municipio349->nombre = 'San Sebastián Teitipac';$municipio349-> distrito_id = 20;$municipio349->save();
        $municipio350 = new Municipio();$municipio350->nombre = 'San Sebastián Tutla';$municipio350-> distrito_id = 19;$municipio350->save();
        $municipio351 = new Municipio();$municipio351->nombre = 'San Simón Almolongas';$municipio351-> distrito_id = 26;$municipio351->save();
        $municipio352 = new Municipio();$municipio352->nombre = 'San Simón Zahuatlán';$municipio352-> distrito_id = 2;$municipio352->save();
        $municipio353 = new Municipio();$municipio353->nombre = 'Santa Ana';$municipio353-> distrito_id = 26;$municipio353->save();
        $municipio354 = new Municipio();$municipio354->nombre = 'Santa Ana Ateixtlahuaca';$municipio354-> distrito_id = 4;$municipio354->save();
        $municipio355 = new Municipio();$municipio355->nombre = 'Santa Ana Cuauhtémoc';$municipio355-> distrito_id = 5;$municipio355->save();
        $municipio356 = new Municipio();$municipio356->nombre = 'Santa Ana del Valle';$municipio356-> distrito_id = 20;$municipio356->save();
        $municipio357 = new Municipio();$municipio357->nombre = 'Santa Ana Tavela';$municipio357-> distrito_id = 27;$municipio357->save();
        $municipio358 = new Municipio();$municipio358->nombre = 'Santa Ana Tlapacoyan';$municipio358-> distrito_id = 18;$municipio358->save();
        $municipio359 = new Municipio();$municipio359->nombre = 'Santa Ana Yareni';$municipio359-> distrito_id = 12;$municipio359->save();
        $municipio360 = new Municipio();$municipio360->nombre = 'Santa Ana Zegache';$municipio360-> distrito_id = 25;$municipio360->save();
        $municipio361 = new Municipio();$municipio361->nombre = 'Santa Catalina Quierí';$municipio361-> distrito_id = 27;$municipio361->save();
        $municipio362 = new Municipio();$municipio362->nombre = 'Santa Catarina Cuixtla';$municipio362-> distrito_id = 26;$municipio362->save();
        $municipio363 = new Municipio();$municipio363->nombre = 'Santa Catarina Ixtepeji';$municipio363-> distrito_id = 12;$municipio363->save();
        $municipio364 = new Municipio();$municipio364->nombre = 'Santa Catarina Juquila';$municipio364-> distrito_id = 22;$municipio364->save();
        $municipio365 = new Municipio();$municipio365->nombre = 'Santa Catarina Lachatao';$municipio365-> distrito_id = 12;$municipio365->save();
        $municipio366 = new Municipio();$municipio366->nombre = 'Santa Catarina Loxicha';$municipio366-> distrito_id = 30;$municipio366->save();
        $municipio367 = new Municipio();$municipio367->nombre = 'Santa Catarina Mechoacán';$municipio367-> distrito_id = 21;$municipio367->save();
        $municipio368 = new Municipio();$municipio368->nombre = 'Santa Catarina Minas';$municipio368-> distrito_id = 25;$municipio368->save();
        $municipio369 = new Municipio();$municipio369->nombre = 'Santa Catarina Quiané';$municipio369-> distrito_id = 18;$municipio369->save();
        $municipio370 = new Municipio();$municipio370->nombre = 'Santa Catarina Tayata';$municipio370-> distrito_id = 16;$municipio370->save();
        $municipio371 = new Municipio();$municipio371->nombre = 'Santa Catarina Ticuá';$municipio371-> distrito_id = 16;$municipio371->save();
        $municipio372 = new Municipio();$municipio372->nombre = 'Santa Catarina Yosonotú';$municipio372-> distrito_id = 16;$municipio372->save();
        $municipio373 = new Municipio();$municipio373->nombre = 'Santa Catarina Zapoquila';$municipio373-> distrito_id = 2;$municipio373->save();
        $municipio374 = new Municipio();$municipio374->nombre = 'Santa Cruz Acatepec';$municipio374-> distrito_id = 4;$municipio374->save();
        $municipio375 = new Municipio();$municipio375->nombre = 'Santa Cruz Amilpas';$municipio375-> distrito_id = 19;$municipio375->save();
        $municipio376 = new Municipio();$municipio376->nombre = 'Santa Cruz de Bravo';$municipio376-> distrito_id = 1;$municipio376->save();
        $municipio377 = new Municipio();$municipio377->nombre = 'Santa Cruz Itundujia';$municipio377-> distrito_id = 15;$municipio377->save();
        $municipio378 = new Municipio();$municipio378->nombre = 'Santa Cruz Mixtepec';$municipio378-> distrito_id = 18;$municipio378->save();
        $municipio379 = new Municipio();$municipio379->nombre = 'Santa Cruz Nundaco';$municipio379-> distrito_id = 16;$municipio379->save();
        $municipio380 = new Municipio();$municipio380->nombre = 'Santa Cruz Papalutla';$municipio380-> distrito_id = 20;$municipio380->save();
        $municipio381 = new Municipio();$municipio381->nombre = 'Santa Cruz Tacache de Mina';$municipio381-> distrito_id = 2;$municipio381->save();
        $municipio382 = new Municipio();$municipio382->nombre = 'Santa Cruz Tacahua';$municipio382-> distrito_id = 16;$municipio382->save();
        $municipio383 = new Municipio();$municipio383->nombre = 'Santa Cruz Tayata';$municipio383-> distrito_id = 16;$municipio383->save();
        $municipio384 = new Municipio();$municipio384->nombre = 'Santa Cruz Xitla';$municipio384-> distrito_id = 26;$municipio384->save();
        $municipio385 = new Municipio();$municipio385->nombre = 'Santa Cruz Xoxocotlán';$municipio385-> distrito_id = 19;$municipio385->save();
        $municipio386 = new Municipio();$municipio386->nombre = 'Santa Cruz Zenzontepec';$municipio386-> distrito_id = 23;$municipio386->save();
        $municipio387 = new Municipio();$municipio387->nombre = 'Santa Gertrudis';$municipio387-> distrito_id = 18;$municipio387->save();
        $municipio388 = new Municipio();$municipio388->nombre = 'Santa Inés del Monte';$municipio388-> distrito_id = 17;$municipio388->save();
        $municipio389 = new Municipio();$municipio389->nombre = 'Santa Inés Yatzeche';$municipio389-> distrito_id = 18;$municipio389->save();
        $municipio390 = new Municipio();$municipio390->nombre = 'Santa Lucía del Camino';$municipio390-> distrito_id = 19;$municipio390->save();
        $municipio391 = new Municipio();$municipio391->nombre = 'Santa Lucía Miahuatlán';$municipio391-> distrito_id = 26;$municipio391->save();
        $municipio392 = new Municipio();$municipio392->nombre = 'Santa Lucía Monteverde';$municipio392-> distrito_id = 15;$municipio392->save();
        $municipio393 = new Municipio();$municipio393->nombre = 'Santa Lucía Ocotlán';$municipio393-> distrito_id = 25;$municipio393->save();
        $municipio394 = new Municipio();$municipio394->nombre = 'Santa María Alotepec';$municipio394-> distrito_id = 14;$municipio394->save();
        $municipio395 = new Municipio();$municipio395->nombre = 'Santa María Apazco';$municipio395-> distrito_id = 10;$municipio395->save();
        $municipio396 = new Municipio();$municipio396->nombre = 'Santa María la Asunción';$municipio396-> distrito_id = 4;$municipio396->save();
        $municipio397 = new Municipio();$municipio397->nombre = 'Heroica Ciudad de Tlaxiaco';$municipio397-> distrito_id = 16;$municipio397->save();
        $municipio398 = new Municipio();$municipio398->nombre = 'Ayoquezco de Aldama';$municipio398-> distrito_id = 18;$municipio398->save();
        $municipio399 = new Municipio();$municipio399->nombre = 'Santa María Atzompa';$municipio399-> distrito_id = 19;$municipio399->save();
        $municipio400 = new Municipio();$municipio400->nombre = 'Santa María Camotlán';$municipio400-> distrito_id = 2;$municipio400->save();
        $municipio401 = new Municipio();$municipio401->nombre = 'Santa María Colotepec';$municipio401-> distrito_id = 30;$municipio401->save();
        $municipio402 = new Municipio();$municipio402->nombre = 'Santa María Cortijo';$municipio402-> distrito_id = 21;$municipio402->save();
        $municipio403 = new Municipio();$municipio403->nombre = 'Santa María Coyotepec';$municipio403-> distrito_id = 19;$municipio403->save();
        $municipio404 = new Municipio();$municipio404->nombre = 'Santa María Chachoápam';$municipio404-> distrito_id = 10;$municipio404->save();
        $municipio405 = new Municipio();$municipio405->nombre = 'Villa de Chilapa de Díaz';$municipio405-> distrito_id = 9;$municipio405->save();
        $municipio406 = new Municipio();$municipio406->nombre = 'Santa María Chilchotla';$municipio406-> distrito_id = 4;$municipio406->save();
        $municipio407 = new Municipio();$municipio407->nombre = 'Santa María Chimalapa';$municipio407-> distrito_id = 29;$municipio407->save();
        $municipio408 = new Municipio();$municipio408->nombre = 'Santa María del Rosario';$municipio408-> distrito_id = 16;$municipio408->save();
        $municipio409 = new Municipio();$municipio409->nombre = 'Santa María del Tule';$municipio409-> distrito_id = 19;$municipio409->save();
        $municipio410 = new Municipio();$municipio410->nombre = 'Santa María Ecatepec';$municipio410-> distrito_id = 27;$municipio410->save();
        $municipio411 = new Municipio();$municipio411->nombre = 'Santa María Guelacé';$municipio411-> distrito_id = 20;$municipio411->save();
        $municipio412 = new Municipio();$municipio412->nombre = 'Santa María Guienagati';$municipio412-> distrito_id = 28;$municipio412->save();
        $municipio413 = new Municipio();$municipio413->nombre = 'Santa María Huatulco';$municipio413-> distrito_id = 30;$municipio413->save();
        $municipio414 = new Municipio();$municipio414->nombre = 'Santa María Huazolotitlán';$municipio414-> distrito_id = 21;$municipio414->save();
        $municipio415 = new Municipio();$municipio415->nombre = 'Santa María Ipalapa';$municipio415-> distrito_id = 15;$municipio415->save();
        $municipio416 = new Municipio();$municipio416->nombre = 'Santa María Ixcatlán';$municipio416-> distrito_id = 4;$municipio416->save();
        $municipio417 = new Municipio();$municipio417->nombre = 'Santa María Jacatepec';$municipio417-> distrito_id = 6;$municipio417->save();
        $municipio418 = new Municipio();$municipio418->nombre = 'Santa María Jalapa del Marqués';$municipio418-> distrito_id = 28;$municipio418->save();
        $municipio419 = new Municipio();$municipio419->nombre = 'Santa María Jaltianguis';$municipio419-> distrito_id = 12;$municipio419->save();
        $municipio420 = new Municipio();$municipio420->nombre = 'Santa María Lachixío';$municipio420-> distrito_id = 23;$municipio420->save();
        $municipio421 = new Municipio();$municipio421->nombre = 'Santa María Mixtequilla';$municipio421-> distrito_id = 28;$municipio421->save();
        $municipio422 = new Municipio();$municipio422->nombre = 'Santa María Nativitas';$municipio422-> distrito_id = 3;$municipio422->save();
        $municipio423 = new Municipio();$municipio423->nombre = 'Santa María Nduayaco';$municipio423-> distrito_id = 9;$municipio423->save();
        $municipio424 = new Municipio();$municipio424->nombre = 'Santa María Ozolotepec';$municipio424-> distrito_id = 26;$municipio424->save();
        $municipio425 = new Municipio();$municipio425->nombre = 'Santa María Pápalo';$municipio425-> distrito_id = 5;$municipio425->save();
        $municipio426 = new Municipio();$municipio426->nombre = 'Santa María Peñoles';$municipio426-> distrito_id = 11;$municipio426->save();
        $municipio427 = new Municipio();$municipio427->nombre = 'Santa María Petapa';$municipio427-> distrito_id = 29;$municipio427->save();
        $municipio428 = new Municipio();$municipio428->nombre = 'Santa María Quiegolani';$municipio428-> distrito_id = 27;$municipio428->save();
        $municipio429 = new Municipio();$municipio429->nombre = 'Santa María Sola';$municipio429-> distrito_id = 23;$municipio429->save();
        $municipio430 = new Municipio();$municipio430->nombre = 'Santa María Tataltepec';$municipio430-> distrito_id = 16;$municipio430->save();
        $municipio431 = new Municipio();$municipio431->nombre = 'Santa María Tecomavaca';$municipio431-> distrito_id = 4;$municipio431->save();
        $municipio432 = new Municipio();$municipio432->nombre = 'Santa María Temaxcalapa';$municipio432-> distrito_id = 13;$municipio432->save();
        $municipio433 = new Municipio();$municipio433->nombre = 'Santa María Temaxcaltepec';$municipio433-> distrito_id = 22;$municipio433->save();
        $municipio434 = new Municipio();$municipio434->nombre = 'Santa María Teopoxco';$municipio434-> distrito_id = 4;$municipio434->save();
        $municipio435 = new Municipio();$municipio435->nombre = 'Santa María Tepantlali';$municipio435-> distrito_id = 14;$municipio435->save();
        $municipio436 = new Municipio();$municipio436->nombre = 'Santa María Texcatitlán';$municipio436-> distrito_id = 5;$municipio436->save();
        $municipio437 = new Municipio();$municipio437->nombre = 'Santa María Tlahuitoltepec';$municipio437-> distrito_id = 14;$municipio437->save();
        $municipio438 = new Municipio();$municipio438->nombre = 'Santa María Tlalixtac';$municipio438-> distrito_id = 5;$municipio438->save();
        $municipio439 = new Municipio();$municipio439->nombre = 'Santa María Tonameca';$municipio439-> distrito_id = 30;$municipio439->save();
        $municipio440 = new Municipio();$municipio440->nombre = 'Santa María Totolapilla';$municipio440-> distrito_id = 28;$municipio440->save();
        $municipio441 = new Municipio();$municipio441->nombre = 'Santa María Xadani';$municipio441-> distrito_id = 29;$municipio441->save();
        $municipio442 = new Municipio();$municipio442->nombre = 'Santa María Yalina';$municipio442-> distrito_id = 13;$municipio442->save();
        $municipio443 = new Municipio();$municipio443->nombre = 'Santa María Yavesía';$municipio443-> distrito_id = 12;$municipio443->save();
        $municipio444 = new Municipio();$municipio444->nombre = 'Santa María Yolotepec';$municipio444-> distrito_id = 16;$municipio444->save();
        $municipio445 = new Municipio();$municipio445->nombre = 'Santa María Yosoyúa';$municipio445-> distrito_id = 16;$municipio445->save();
        $municipio446 = new Municipio();$municipio446->nombre = 'Santa María Yucuhiti';$municipio446-> distrito_id = 16;$municipio446->save();
        $municipio447 = new Municipio();$municipio447->nombre = 'Santa María Zacatepec';$municipio447-> distrito_id = 15;$municipio447->save();
        $municipio448 = new Municipio();$municipio448->nombre = 'Santa María Zaniza';$municipio448-> distrito_id = 23;$municipio448->save();
        $municipio449 = new Municipio();$municipio449->nombre = 'Santa María Zoquitlán';$municipio449-> distrito_id = 20;$municipio449->save();
        $municipio450 = new Municipio();$municipio450->nombre = 'Santiago Amoltepec';$municipio450-> distrito_id = 23;$municipio450->save();
        $municipio451 = new Municipio();$municipio451->nombre = 'Santiago Apoala';$municipio451-> distrito_id = 10;$municipio451->save();
        $municipio452 = new Municipio();$municipio452->nombre = 'Santiago Apóstol';$municipio452-> distrito_id = 25;$municipio452->save();
        $municipio453 = new Municipio();$municipio453->nombre = 'Santiago Astata';$municipio453-> distrito_id = 28;$municipio453->save();
        $municipio454 = new Municipio();$municipio454->nombre = 'Santiago Atitlán';$municipio454-> distrito_id = 14;$municipio454->save();
        $municipio455 = new Municipio();$municipio455->nombre = 'Santiago Ayuquililla';$municipio455-> distrito_id = 2;$municipio455->save();
        $municipio456 = new Municipio();$municipio456->nombre = 'Santiago Cacaloxtepec';$municipio456-> distrito_id = 2;$municipio456->save();
        $municipio457 = new Municipio();$municipio457->nombre = 'Santiago Camotlán';$municipio457-> distrito_id = 13;$municipio457->save();
        $municipio458 = new Municipio();$municipio458->nombre = 'Santiago Comaltepec';$municipio458-> distrito_id = 12;$municipio458->save();
        $municipio459 = new Municipio();$municipio459->nombre = 'Santiago Chazumba';$municipio459-> distrito_id = 2;$municipio459->save();
        $municipio460 = new Municipio();$municipio460->nombre = 'Santiago Choápam';$municipio460-> distrito_id = 7;$municipio460->save();
        $municipio461 = new Municipio();$municipio461->nombre = 'Santiago del Río';$municipio461-> distrito_id = 1;$municipio461->save();
        $municipio462 = new Municipio();$municipio462->nombre = 'Santiago Huajolotitlán';$municipio462-> distrito_id = 2;$municipio462->save();
        $municipio463 = new Municipio();$municipio463->nombre = 'Santiago Huauclilla';$municipio463-> distrito_id = 10;$municipio463->save();
        $municipio464 = new Municipio();$municipio464->nombre = 'Santiago Ihuitlán Plumas';$municipio464-> distrito_id = 3;$municipio464->save();
        $municipio465 = new Municipio();$municipio465->nombre = 'Santiago Ixcuintepec';$municipio465-> distrito_id = 14;$municipio465->save();
        $municipio466 = new Municipio();$municipio466->nombre = 'Santiago Ixtayutla';$municipio466-> distrito_id = 21;$municipio466->save();
        $municipio467 = new Municipio();$municipio467->nombre = 'Santiago Jamiltepec';$municipio467-> distrito_id = 21;$municipio467->save();
        $municipio468 = new Municipio();$municipio468->nombre = 'Santiago Jocotepec';$municipio468-> distrito_id = 7;$municipio468->save();
        $municipio469 = new Municipio();$municipio469->nombre = 'Santiago Juxtlahuaca';$municipio469-> distrito_id = 8;$municipio469->save();
        $municipio470 = new Municipio();$municipio470->nombre = 'Santiago Lachiguiri';$municipio470-> distrito_id = 28;$municipio470->save();
        $municipio471 = new Municipio();$municipio471->nombre = 'Santiago Lalopa';$municipio471-> distrito_id = 13;$municipio471->save();
        $municipio472 = new Municipio();$municipio472->nombre = 'Santiago Laollaga';$municipio472-> distrito_id = 28;$municipio472->save();
        $municipio473 = new Municipio();$municipio473->nombre = 'Santiago Laxopa';$municipio473-> distrito_id = 12;$municipio473->save();
        $municipio474 = new Municipio();$municipio474->nombre = 'Santiago Llano Grande';$municipio474-> distrito_id = 21;$municipio474->save();
        $municipio475 = new Municipio();$municipio475->nombre = 'Santiago Matatlán';$municipio475-> distrito_id = 20;$municipio475->save();
        $municipio476 = new Municipio();$municipio476->nombre = 'Santiago Miltepec';$municipio476-> distrito_id = 2;$municipio476->save();
        $municipio477 = new Municipio();$municipio477->nombre = 'Santiago Minas';$municipio477-> distrito_id = 23;$municipio477->save();
        $municipio478 = new Municipio();$municipio478->nombre = 'Santiago Nacaltepec';$municipio478-> distrito_id = 5;$municipio478->save();
        $municipio479 = new Municipio();$municipio479->nombre = 'Santiago Nejapilla';$municipio479-> distrito_id = 9;$municipio479->save();
        $municipio480 = new Municipio();$municipio480->nombre = 'Santiago Nundiche';$municipio480-> distrito_id = 16;$municipio480->save();
        $municipio481 = new Municipio();$municipio481->nombre = 'Santiago Nuyoó';$municipio481-> distrito_id = 16;$municipio481->save();
        $municipio482 = new Municipio();$municipio482->nombre = 'Santiago Pinotepa Nacional';$municipio482-> distrito_id = 21;$municipio482->save();
        $municipio483 = new Municipio();$municipio483->nombre = 'Santiago Suchilquitongo';$municipio483-> distrito_id = 11;$municipio483->save();
        $municipio484 = new Municipio();$municipio484->nombre = 'Santiago Tamazola';$municipio484-> distrito_id = 1;$municipio484->save();
        $municipio485 = new Municipio();$municipio485->nombre = 'Santiago Tapextla';$municipio485-> distrito_id = 21;$municipio485->save();
        $municipio486 = new Municipio();$municipio486->nombre = 'Villa Tejúpam de la Unión';$municipio486-> distrito_id = 9;$municipio486->save();
        $municipio487 = new Municipio();$municipio487->nombre = 'Santiago Tenango';$municipio487-> distrito_id = 11;$municipio487->save();
        $municipio488 = new Municipio();$municipio488->nombre = 'Santiago Tepetlapa';$municipio488-> distrito_id = 3;$municipio488->save();
        $municipio489 = new Municipio();$municipio489->nombre = 'Santiago Tetepec';$municipio489-> distrito_id = 21;$municipio489->save();
        $municipio490 = new Municipio();$municipio490->nombre = 'Santiago Texcalcingo';$municipio490-> distrito_id = 4;$municipio490->save();
        $municipio491 = new Municipio();$municipio491->nombre = 'Santiago Textitlán';$municipio491-> distrito_id = 23;$municipio491->save();
        $municipio492 = new Municipio();$municipio492->nombre = 'Santiago Tilantongo';$municipio492-> distrito_id = 10;$municipio492->save();
        $municipio493 = new Municipio();$municipio493->nombre = 'Santiago Tillo';$municipio493-> distrito_id = 10;$municipio493->save();
        $municipio494 = new Municipio();$municipio494->nombre = 'Santiago Tlazoyaltepec';$municipio494-> distrito_id = 11;$municipio494->save();
        $municipio495 = new Municipio();$municipio495->nombre = 'Santiago Xanica';$municipio495-> distrito_id = 26;$municipio495->save();
        $municipio496 = new Municipio();$municipio496->nombre = 'Santiago Xiacuí';$municipio496-> distrito_id = 12;$municipio496->save();
        $municipio497 = new Municipio();$municipio497->nombre = 'Santiago Yaitepec';$municipio497-> distrito_id = 22;$municipio497->save();
        $municipio498 = new Municipio();$municipio498->nombre = 'Santiago Yaveo';$municipio498-> distrito_id = 7;$municipio498->save();
        $municipio499 = new Municipio();$municipio499->nombre = 'Santiago Yolomécatl';$municipio499-> distrito_id = 9;$municipio499->save();
        $municipio500 = new Municipio();$municipio500->nombre = 'Santiago Yosondúa';$municipio500-> distrito_id = 16;$municipio500->save();
        $municipio501 = new Municipio();$municipio501->nombre = 'Santiago Yucuyachi';$municipio501-> distrito_id = 1;$municipio501->save();
        $municipio502 = new Municipio();$municipio502->nombre = 'Santiago Zacatepec';$municipio502-> distrito_id = 14;$municipio502->save();
        $municipio503 = new Municipio();$municipio503->nombre = 'Santiago Zoochila';$municipio503-> distrito_id = 13;$municipio503->save();
        $municipio504 = new Municipio();$municipio504->nombre = 'Nuevo Zoquiápam';$municipio504-> distrito_id = 12;$municipio504->save();
        $municipio505 = new Municipio();$municipio505->nombre = 'Santo Domingo Ingenio';$municipio505-> distrito_id = 29;$municipio505->save();
        $municipio506 = new Municipio();$municipio506->nombre = 'Santo Domingo Albarradas';$municipio506-> distrito_id = 20;$municipio506->save();
        $municipio507 = new Municipio();$municipio507->nombre = 'Santo Domingo Armenta';$municipio507-> distrito_id = 21;$municipio507->save();
        $municipio508 = new Municipio();$municipio508->nombre = 'Santo Domingo Chihuitán';$municipio508-> distrito_id = 28;$municipio508->save();
        $municipio509 = new Municipio();$municipio509->nombre = 'Santo Domingo de Morelos';$municipio509-> distrito_id = 30;$municipio509->save();
        $municipio510 = new Municipio();$municipio510->nombre = 'Santo Domingo Ixcatlán';$municipio510-> distrito_id = 16;$municipio510->save();
        $municipio511 = new Municipio();$municipio511->nombre = 'Santo Domingo Nuxaá';$municipio511-> distrito_id = 10;$municipio511->save();
        $municipio512 = new Municipio();$municipio512->nombre = 'Santo Domingo Ozolotepec';$municipio512-> distrito_id = 26;$municipio512->save();
        $municipio513 = new Municipio();$municipio513->nombre = 'Santo Domingo Petapa';$municipio513-> distrito_id = 29;$municipio513->save();
        $municipio514 = new Municipio();$municipio514->nombre = 'Santo Domingo Roayaga';$municipio514-> distrito_id = 13;$municipio514->save();
        $municipio515 = new Municipio();$municipio515->nombre = 'Santo Domingo Tehuantepec';$municipio515-> distrito_id = 28;$municipio515->save();
        $municipio516 = new Municipio();$municipio516->nombre = 'Santo Domingo Teojomulco';$municipio516-> distrito_id = 23;$municipio516->save();
        $municipio517 = new Municipio();$municipio517->nombre = 'Santo Domingo Tepuxtepec';$municipio517-> distrito_id = 14;$municipio517->save();
        $municipio518 = new Municipio();$municipio518->nombre = 'Santo Domingo Tlatayápam';$municipio518-> distrito_id = 9;$municipio518->save();
        $municipio519 = new Municipio();$municipio519->nombre = 'Santo Domingo Tomaltepec';$municipio519-> distrito_id = 19;$municipio519->save();
        $municipio520 = new Municipio();$municipio520->nombre = 'Santo Domingo Tonalá';$municipio520-> distrito_id = 2;$municipio520->save();
        $municipio521 = new Municipio();$municipio521->nombre = 'Santo Domingo Tonaltepec';$municipio521-> distrito_id = 9;$municipio521->save();
        $municipio522 = new Municipio();$municipio522->nombre = 'Santo Domingo Xagacía';$municipio522-> distrito_id = 13;$municipio522->save();
        $municipio523 = new Municipio();$municipio523->nombre = 'Santo Domingo Yanhuitlán';$municipio523-> distrito_id = 10;$municipio523->save();
        $municipio524 = new Municipio();$municipio524->nombre = 'Santo Domingo Yodohino';$municipio524-> distrito_id = 2;$municipio524->save();
        $municipio525 = new Municipio();$municipio525->nombre = 'Santo Domingo Zanatepec';$municipio525-> distrito_id = 29;$municipio525->save();
        $municipio526 = new Municipio();$municipio526->nombre = 'Santos Reyes Nopala';$municipio526-> distrito_id = 22;$municipio526->save();
        $municipio527 = new Municipio();$municipio527->nombre = 'Santos Reyes Pápalo';$municipio527-> distrito_id = 5;$municipio527->save();
        $municipio528 = new Municipio();$municipio528->nombre = 'Santos Reyes Tepejillo';$municipio528-> distrito_id = 8;$municipio528->save();
        $municipio529 = new Municipio();$municipio529->nombre = 'Santos Reyes Yucuná';$municipio529-> distrito_id = 2;$municipio529->save();
        $municipio530 = new Municipio();$municipio530->nombre = 'Santo Tomás Jalieza';$municipio530-> distrito_id = 25;$municipio530->save();
        $municipio531 = new Municipio();$municipio531->nombre = 'Santo Tomás Mazaltepec';$municipio531-> distrito_id = 11;$municipio531->save();
        $municipio532 = new Municipio();$municipio532->nombre = 'Santo Tomás Ocotepec';$municipio532-> distrito_id = 16;$municipio532->save();
        $municipio533 = new Municipio();$municipio533->nombre = 'Santo Tomás Tamazulapan';$municipio533-> distrito_id = 26;$municipio533->save();
        $municipio534 = new Municipio();$municipio534->nombre = 'San Vicente Coatlán';$municipio534-> distrito_id = 24;$municipio534->save();
        $municipio535 = new Municipio();$municipio535->nombre = 'San Vicente Lachixío';$municipio535-> distrito_id = 23;$municipio535->save();
        $municipio536 = new Municipio();$municipio536->nombre = 'San Vicente Nuñú';$municipio536-> distrito_id = 9;$municipio536->save();
        $municipio537 = new Municipio();$municipio537->nombre = 'Silacayoápam';$municipio537-> distrito_id = 1;$municipio537->save();
        $municipio538 = new Municipio();$municipio538->nombre = 'Sitio de Xitlapehua';$municipio538-> distrito_id = 26;$municipio538->save();
        $municipio539 = new Municipio();$municipio539->nombre = 'Soledad Etla';$municipio539-> distrito_id = 11;$municipio539->save();
        $municipio540 = new Municipio();$municipio540->nombre = 'Villa de Tamazulápam del Progreso';$municipio540-> distrito_id = 9;$municipio540->save();
        $municipio541 = new Municipio();$municipio541->nombre = 'Tanetze de Zaragoza';$municipio541-> distrito_id = 13;$municipio541->save();
        $municipio542 = new Municipio();$municipio542->nombre = 'Taniche';$municipio542-> distrito_id = 24;$municipio542->save();
        $municipio543 = new Municipio();$municipio543->nombre = 'Tataltepec de Valdés';$municipio543-> distrito_id = 22;$municipio543->save();
        $municipio544 = new Municipio();$municipio544->nombre = 'Teococuilco de Marcos Pérez';$municipio544-> distrito_id = 12;$municipio544->save();
        $municipio545 = new Municipio();$municipio545->nombre = 'Teotitlán de Flores Magón';$municipio545-> distrito_id = 4;$municipio545->save();
        $municipio546 = new Municipio();$municipio546->nombre = 'Teotitlán del Valle';$municipio546-> distrito_id = 20;$municipio546->save();
        $municipio547 = new Municipio();$municipio547->nombre = 'Teotongo';$municipio547-> distrito_id = 9;$municipio547->save();
        $municipio548 = new Municipio();$municipio548->nombre = 'Tepelmeme Villa de Morelos';$municipio548-> distrito_id = 3;$municipio548->save();
        $municipio549 = new Municipio();$municipio549->nombre = 'Heroica Villa de Tezoatlán de Segura y Luna, Cuna de la Independencia de Oaxaca';$municipio549-> distrito_id = 2;$municipio549->save();
        $municipio550 = new Municipio();$municipio550->nombre = 'San Jerónimo Tlacochahuaya';$municipio550-> distrito_id = 20;$municipio550->save();
        $municipio551 = new Municipio();$municipio551->nombre = 'Tlacolula de Matamoros';$municipio551-> distrito_id = 20;$municipio551->save();
        $municipio552 = new Municipio();$municipio552->nombre = 'Tlacotepec Plumas';$municipio552-> distrito_id = 3;$municipio552->save();
        $municipio553 = new Municipio();$municipio553->nombre = 'Tlalixtac de Cabrera';$municipio553-> distrito_id = 19;$municipio553->save();
        $municipio554 = new Municipio();$municipio554->nombre = 'Totontepec Villa de Morelos';$municipio554-> distrito_id = 14;$municipio554->save();
        $municipio555 = new Municipio();$municipio555->nombre = 'Trinidad Zaachila';$municipio555-> distrito_id = 17;$municipio555->save();
        $municipio556 = new Municipio();$municipio556->nombre = 'La Trinidad Vista Hermosa';$municipio556-> distrito_id = 9;$municipio556->save();
        $municipio557 = new Municipio();$municipio557->nombre = 'Unión Hidalgo';$municipio557-> distrito_id = 29;$municipio557->save();
        $municipio558 = new Municipio();$municipio558->nombre = 'Valerio Trujano';$municipio558-> distrito_id = 5;$municipio558->save();
        $municipio559 = new Municipio();$municipio559->nombre = 'San Juan Bautista Valle Nacional';$municipio559-> distrito_id = 6;$municipio559->save();
        $municipio560 = new Municipio();$municipio560->nombre = 'Villa Díaz Ordaz';$municipio560-> distrito_id = 20;$municipio560->save();
        $municipio561 = new Municipio();$municipio561->nombre = 'Yaxe';$municipio561-> distrito_id = 25;$municipio561->save();
        $municipio562 = new Municipio();$municipio562->nombre = 'Magdalena Yodocono de Porfirio Díaz';$municipio562-> distrito_id = 10;$municipio562->save();
        $municipio563 = new Municipio();$municipio563->nombre = 'Yogana';$municipio563-> distrito_id = 24;$municipio563->save();
        $municipio564 = new Municipio();$municipio564->nombre = 'Yutanduchi de Guerrero';$municipio564-> distrito_id = 10;$municipio564->save();
        $municipio565 = new Municipio();$municipio565->nombre = 'Villa de Zaachila';$municipio565-> distrito_id = 17;$municipio565->save();
        $municipio566 = new Municipio();$municipio566->nombre = 'San Mateo Yucutindoo';$municipio566-> distrito_id = 23;$municipio566->save();
        $municipio567 = new Municipio();$municipio567->nombre = 'Zapotitlán Lagunas';$municipio567-> distrito_id = 1;$municipio567->save();
        $municipio568 = new Municipio();$municipio568->nombre = 'Zapotitlán Palmas';$municipio568-> distrito_id = 2;$municipio568->save();
        $municipio569 = new Municipio();$municipio569->nombre = 'Santa Inés de Zaragoza';$municipio569-> distrito_id = 10;$municipio569->save();
        $municipio570 = new Municipio();$municipio570->nombre = 'Zimatlán de Álvarez';$municipio570-> distrito_id = 18;$municipio570->save();
        


    }
}
